### ISSUE TITLE
Dataset missing for dti_tdc_dg

### ISSUE THREAD

**Issue by JudeWells** [navid-naderi/PLM_SWE#3]
Great repo I managed to run most of the benchmarks with no problem except for dti_tdc_dg
I note that the data for dti_tdc_dg is not downloaded by `download_data.py` and it throws an error when running the command as listed, looking zip file that was downloaded I see that it is zero bytes.
```
(plm_swe) judewells@kaspian:~/Documents/jw_PLM_SWE/PLM_SWE$ python run_dti.py --run-id dti_tdc_dg_swepooling_128refpoints_128slices_esm2_8m --config config/dti_tdc_dg.yaml --num-ref-points 128 --num-slices 128 --target-model-type esm2_t6_8M_UR50D
/home/judewells/miniconda3/envs/plm_swe/lib/python3.11/site-packages/transformers/utils/generic.py:311: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
2024-10-03 20:47:24,467 [INFO] Using CUDA device cuda:0
2024-10-03 20:47:24,467 [DEBUG] Setting random seed 12345
2024-10-03 20:47:24,468 [INFO] Preparing DataModule
Downloading Benchmark Group...
0.00iB [00:00, ?iB/s]
Extracting zip file...
Traceback (most recent call last):
  File "/home/judewells/Documents/jw_PLM_SWE/PLM_SWE/run_dti.py", line 497, in <module>
    best_model = main()
                 ^^^^^^
  File "/home/judewells/Documents/jw_PLM_SWE/PLM_SWE/run_dti.py", line 274, in main
    datamodule.prepare_data()
  File "/home/judewells/Documents/jw_PLM_SWE/PLM_SWE/data/datamodules.py", line 458, in prepare_data
    dg_group = dti_dg_group(path=self._data_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judewells/miniconda3/envs/plm_swe/lib/python3.11/site-packages/tdc/benchmark_group/dti_dg_group.py", line 17, in __init__
    super().__init__(name="DTI_DG_Group", path=path, file_format="csv")
  File "/home/judewells/miniconda3/envs/plm_swe/lib/python3.11/site-packages/tdc/benchmark_group/base_group.py", line 44, in __init__
    self.name = bm_group_load(name, path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judewells/miniconda3/envs/plm_swe/lib/python3.11/site-packages/tdc/utils/load.py", line 585, in bm_group_load
    name = bm_download_wrapper(name, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judewells/miniconda3/envs/plm_swe/lib/python3.11/site-packages/tdc/utils/load.py", line 266, in bm_download_wrapper
    with ZipFile(os.path.join(path, name + ".zip"), "r") as zip:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/judewells/miniconda3/envs/plm_swe/lib/python3.11/zipfile.py", line 1313, in __init__
    self._RealGetContents()
  File "/home/judewells/miniconda3/envs/plm_swe/lib/python3.11/zipfile.py", line 1380, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by navid-naderi** [comment]
Thank you, Jude. I tried to recreate the error you highlighted here, but it seems that downloading the TDC data works on my machine as long as the folder `datasets` exists under the main directory (see below); you are correct that `download_data.py` only focuses on the rest of the tasks, since the DTI-DG dataset gets automatically downloaded the first time the corresponding task is run.

Could you please make sure the library versions are similar to what is specified in `requirements.txt` (esp. the PyTDC version being 0.3.9)?

```
$ python run_dti.py --run-id dti_tdc_dg_swepooling_128refpoints_128slices_esm2_8m --config config/dti_tdc_dg.yaml --num-ref-points 128 --num-slices 128 --target-model-type esm2_t6_8M_UR50D
2024-10-07 15:45:26,886 [INFO] Using CUDA device cuda:0
2024-10-07 15:45:26,886 [DEBUG] Setting random seed 12345
2024-10-07 15:45:26,888 [INFO] Preparing DataModule
Downloading Benchmark Group...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.52M/9.52M [00:01<00:00, 5.12MiB/s]
Extracting zip file...
Done!
```
